### PR TITLE
Fixes to awards-bot

### LINKED ISSUE #25: Update functions that use the NCEAS/RT package
Bryce is re-writing a bunch of the `NCEAS/rt` functions.

### PR DESCRIPTION
**Pull request by laijasmine**
- Deals with changes in the RT package, resolves #25 
- Fixes issue from: `Error in UseMethod("months") : no applicable method for 'months' applied to an object of class "character"`

### CODE REVIEW

**Comment by laijasmine** [comment]
Chris - I think I found the source of the problem that it was reading in the `Sys.getenv` variables as characters instead of numeric. Made some changes.. hopefully we can test this out some time.

File: R/RT_functions.R [hunk 1]
```diff
@@ -208,20 +203,6 @@ send_correspondence_at_time_x <- function(awards_db,
   
 }
 
-  
-## helper function to check RT replies
```
Comment (csjx) [inline R/RT_functions.R:211]: @laijasmine - What was the reason for removing `check_rt_reply()`? It seems useful to report to the Slack channel when things aren't working as expected.  Is there a problem on the RT side?  When you can, add a detail paragraph to your commits after the short one-line description so we know what the rationale is for each commit (other than minor formatting or typo fix commits).

File: R/main.R [hunk 2]
```diff
@@ -5,6 +5,12 @@ main <- function(database_path = Sys.getenv('DATABASE_PATH'),
                  annual_report_time = Sys.getenv('ANNUAL_REPORT_TIME'),
                  initial_aon_offset = Sys.getenv('INITIAL_AON_OFFSET'),
                  aon_recurring_interval = Sys.getenv('AON_RECURRING_INTERVAL')) {
+
```
Comment (csjx) [inline R/main.R:8]: Looks good 👍 - thanks for fixing the return type.

File: R/main.R [hunk 3]
```diff
@@ -31,11 +37,17 @@ test_main <- function(database_path = Sys.getenv('DATABASE_PATH'),
...
+  annual_report_time <-  as.numeric(annual_report_time)
+  initial_aon_offset <-  as.numeric(initial_aon_offset)
+  aon_recurring_interval <-  as.numeric(aon_recurring_interval)
+  
   # Change email to testing email 
   db <- import_awards_db(database_path)
   db$pi_email <- email
   utils::write.csv(db, database_path, row.names = FALSE)
   
+  #runs fine individually but has issues when run from the top
```
Comment (csjx) [inline R/main.R]: Is this a bug comment?  If so, let's make a Github issue.

File: tests/testthat/test_RT_functions.R [hunk 4]
```diff
@@ -18,20 +18,20 @@ test_that('we can create an RT ticket', {
...
-    skip('Run slackr_setup() to run this test')
-  }
-  
-  db <- create_dummy_database()
-  ticket <- create_ticket(db$id, db$pi_email)
-  
-  # create_ticket ouputs the character 'error' when it fails
-  expect_equal(ticket, 'rt_ticket_create_error')
-})
+# test_that('create_ticket errors gracefully', {
```
Comment (csjx) [inline tests/testthat/test_RT_functions.R]: Again, please explain why you're removing the unit test in your commit detail paragraph - it's hard to know what's failing here.

File: R/RT_functions.R [hunk 5]
```diff
@@ -37,16 +37,6 @@ create_ticket <- function(award, requestor) {
                                  subject = subject,
                                  rt_base = 'https://support.nceas.ucsb.edu/rt')
 
-   # if (!grepl('created', httr::content(ticket))) {
```
Comment (csjx) [inline R/RT_functions.R]: Can you explain in your commit what the RT package isn't supporting?

File: tests/testthat/test_RT_functions.R [hunk 6]
```diff
@@ -18,21 +18,6 @@ test_that('we can create an RT ticket', {
   expect_type(ticket, 'character')
 })
 
-# test_that('create_ticket errors gracefully', {
```
Comment (csjx) [inline tests/testthat/test_RT_functions.R]: Same here - if RT is failing these calls, let's add Github tickets rather than removing the work, and we can discuss what to do.

File: tests/testthat/test_RT_functions.R [hunk 7]
```diff
@@ -10,24 +11,11 @@ test_that('we can create an RT ticket', {
...
-test_that('create_ticket errors gracefully', {
-  if (check_rt_login(rt_url)) {
-    skip('Logged in to RT. Test will probably not pass')
-  }
-  if (Sys.getenv('SLACK_WEBHOOK_URL') == '') {
-    skip('Run slackr_setup() to run this test')
-  }
-  
-  db <- create_dummy_database()
+  #does not return ticket but creates ticket
```
Comment (csjx) [inline tests/testthat/test_RT_functions.R:15]: If `create_ticket()` doesn't return the ticket, what does it return? Instead of removing the functionality, can we get the ticket based on what is returned (like the `id`)?

**Review by csjx — CHANGES_REQUESTED** [review]
Heya @laijasmine - Let's chat about these changes, particularly the RT calls not working.  See my comments in the code.  Also, try to be more verbose in your commits (one-line title, followed by a second line or paragraph explaining the details).  Thanks for getting rolling on this!

**Comment by laijasmine** [comment]
@csjx sounds good I'll work through this later today to give more detailed explanations

File: R/RT_functions.R (hunk 1 above)
Comment (laijasmine) [reply R/RT_functions.R:211]: Thanks Chris! Will definitely do that going forward. My apologies for having you review this without much context.

This is an issue with the `RT` package. I checked the most recent version here for the [`rt_ticket_history_reply` ](https://github.com/NCEAS/rt/blob/master/R/rt_ticket_history_reply.R) function and it now only returns the ticket id and not all the information as before (ie. `reply$status_code`). Therefore, the `check_rt_reply` no longer works as intended because it is dependent on the other information that is returned in older versions of this function.

File: R/main.R (hunk 3 above)
Comment (laijasmine) [reply R/main.R]: I'll remove it!  This was an issue I had running it locally on my Mac that I made a note to myself when initially was getting to know the bot. I must have committed it by accident.

File: tests/testthat/test_RT_functions.R (hunk 7 above)
Comment (laijasmine) [reply tests/testthat/test_RT_functions.R:15]: I removed the part of this test that involves the same rt problem with `rt_ticket_history_reply` in the `create_ticket` code where it no longer gives the error code. Without the error code, I can't check if it creates the `rt_ticket_create_error` object. So now I have changed the test to see if a ticket to see if `create_ticket` indeed returns some character object (the ticket `id`)

Comment (amoeba) [reply tests/testthat/test_RT_functions.R:15]: (Jump jumping in here with a note on the change in the `rt` package behavior we introduced for the first release: If `rt_ticket_history_reply` fails, it _should_ throw a `stop` which can be `tryCatch`'d. The error message, if one was sent back by RT, will be available in the `tryCatch`. If it's not, let us know over on https://github.com/NCEAS/rt and we can put in a workaround).

Comment (laijasmine) [reply tests/testthat/test_RT_functions.R:15]: Oh nice I will look into that! I should have asked earlier! Thanks Bryce

File: R/RT_functions.R (hunk 5 above)
Comment (laijasmine) [reply R/RT_functions.R]: fixed to support the new changes in RT

File: tests/testthat/test_RT_functions.R (hunk 6 above)
Comment (laijasmine) [reply tests/testthat/test_RT_functions.R]: #25

File: tests/testthat/test_RT_functions.R (hunk 7 above)
Comment (csjx) [reply tests/testthat/test_RT_functions.R:15]: Thanks @amoeba !

**Comment by laijasmine** [comment]
@csjx no rush on this. I finally got back to this and brought back the `check_rt_reply` function. The difficulty is figuring how to test when it errors. I haven't figured out any good solutions to force RT to throw an error so any ideas on that would be great.

File: R/RT_functions.R (hunk 1 above)
Comment (laijasmine) [reply R/RT_functions.R:211]: tried to fixed in subsequent updates

File: R/RT_functions.R [hunk 8]
```diff
@@ -37,17 +37,14 @@ create_ticket <- function(award, requestor) {
                                  subject = subject,
                                  rt_base = 'https://support.nceas.ucsb.edu/rt')
   
-  if (!grepl('created', httr::content(ticket))) {
-    out <- sprintf('I failed to create a ticket for award: %s, from requestor: %s', award, requestor)
-    slackr::slackr_bot(out)
-    return('rt_ticket_create_error')
+  #check to see if the object ticket is created successfully
+  if(!exists("ticket")) {
```
Comment (csjx) [inline R/RT_functions.R:41]: Hi Jasmine, are you testing for the existence of the string "ticket" here? I'm not quite following that. Perhaps that should be unquoted to be the ticket variable?

**Review by csjx — APPROVED** [review]
Heya Jasmine, I finally had a look at these changes. Looks good other than my one minor comment about testing for a string existence. Let's fix that and move forward on deploying this.

File: R/RT_functions.R (hunk 8 above)
Comment (laijasmine) [reply R/RT_functions.R:41]: Thanks Chris! Will look at this as soon as I can.

Comment (laijasmine) [reply R/RT_functions.R:41]: ~~finally looked at it. Looks like it was a mistake on my part and I have fixed it in the updated commit. Thanks for catching that!~~

Me 3 hours ago wasn't thinking very clearly.

The `exists` function looks to see if the object `ticket` was created successfully. It takes a character string.

**Comment by laijasmine** [comment]
@csjx Need to investigate one weird problem I ran into today. Not sure why the `test_main` function is emailing the PIs when the given example database only has 2 records and should only email me. Not aware that I'm doing anything different from how I have been testing in the past or how it is outlined in the readme. Will see if I can find the cause by just tracing the code.

**Comment by laijasmine** [comment]
Ok figured it out. Turns out I was accidentally referring to an older awards database from previous testing and was updating the awards database with new awards. I updated the readme file is clear on how to do that from the test_main.R and others in the future shouldn't run into this issue.

I'll merge this file once the checks are complete. @csjx  Let me know what the next steps should be.

File: R/RT_functions.R (hunk 8 above)
Comment (csjx) [reply R/RT_functions.R:41]: gotcha! 👍
